// ***** AUTO-GENERATED FILE. DO NOT EDIT. *****
// Generated by gen_addrs.py

`timescale 1ns/1ps
`default_nettype none

/**
 * MMI address map
 */
package MMI_ADDRS_HSD;
    parameter int MMI_ADDRLEN  = 15;
    parameter int MMI_DATALEN  = 16;
    parameter bit MMI_BYTE_ADDRESSED = 0;
    typedef enum {
        MMI_HSDCTRL,                    //  0
        MMI_OBC_SSD_READ,               //  1
        MMI_OBC_SSD_WRITE,              //  2
        MMI_TDI_RXDBUF,                 //  3
        MMI_TDI_TXDBUF,                 //  4
        MMI_IRQCTRL,                    //  5
        MMI_SEMCTRL,                    //  6
        MMI_LM71CTRL0,                  //  7
        MMI_LM71CTRL1,                  //  8
        MMI_LMKCLK,                     //  9
        MMI_FE_ADC,                     // 10
        MMI_ZYNQ_FW_EVENTS,             // 11
        MMI_MMI_FW_EVENTS,              // 12
        MMI_MMI_FW,                     // 13
        MMI_PS_MASTER,                  // 14
        MMI_GLOBAL_ALARM,               // 15
        MMI_CPMCTRL0,                   // 16
        MMI_CPMCTRL1,                   // 17
        MMI_RXADC,                      // 18
        MMI_RXAMP,                      // 19
        MMI_RXADCDATA,                  // 20
        MMI_RXDATA,                     // 21
        MMI_RXDSP,                      // 22
        MMI_UPI_RXDEMOD,                // 23
        MMI_RXFIFO,                     // 24
        MMI_TXDATA,                     // 25
        MMI_TXDSP,                      // 26
        MMI_UPI_TXMOD,                  // 27
        MMI_TXSDR_TXBUF,                // 28
        MMI_RX_PWR_PREFILT,             // 29
        MMI_RX_PWR_POSTFILT,            // 30
        MMI_UPI_POLL,                   // 31
        MMI_RX_BBFILT,                  // 32
        MMI_TXDAC,                      // 33
        MMI_TXDAC_JESD,                 // 34
        MMI_FE_SYNTHRX,                 // 35
        MMI_FE_SYNTHTX,                 // 36
        MMI_PCH_TEMP_LIMIT,             // 37
        MMI_HDR_TEMP_LIMIT,             // 38
        MMI_KAS_TEMP_LIMIT,             // 39
        MMI_SCRATCH,                    // 40
        MMI_IRQ_TEST,                   // 41
        MMI_HDR_CPM,                    // 42
        MMI_BP_IO,                      // 43
        MMI_RGMII,                      // 44
        MMI_MDIO_CTRL,                  // 45
        MMI_BP_IO_SEC,                  // 46
        MMI_BP_CPM,                     // 47
        MMI_NIC_SDR,                    // 48
        MMI_P4_FWD,                     // 49
        MMI_MPLS_SIMPLETOGA,            // 50
        MMI_MPLS_ROUTER,                // 51
        MMI_NICHDR_CTRL,                // 52
        MMI_RFOE_CTRL,                  // 53
        MMI_SATA_CTRL,                  // 54
        MMI_SATA_DRP,                   // 55
        MMI_SATA_PERF,                  // 56
        MMI_SATA_TRAFFIC_GEN,           // 57
        MMI_IDEV_COPY,                  // 58
        MMI_PS_SSD_CTRL,                // 59
        MMI_SYSMON,                     // 60
        MMI_ZYNQ_SOFT_QSPI,             // 61
        MMI_PSIRQCTRL,                  // 62
        MMI_ZYNQ_IRQ_TEST,              // 63
        MMI_QSPI_BB,                    // 64
        MMI_QSPI_TRAFFIC_GEN,           // 65
        MMI_QSPI_PERF,                  // 66
        MMI_CPMCTRL0_VLIM,              // 67
        MMI_CPMCTRL1_VLIM,              // 68
        MMI_HDR_CPM_VLIM,               // 69
        MMI_BP_CPM_VLIM,                // 70
        MMI_CPMCTRL0_MAXVAL,            // 71
        MMI_CPMCTRL1_MAXVAL,            // 72
        MMI_HDR_CPM_MAXVAL,             // 73
        MMI_BP_CPM_MAXVAL,              // 74
        MMI_TXREPLAY,                   // 75
        MMI_TXNCO,                      // 76
        MMI_I2C_CLK_DIV,                // 77
        MMI_DDR_CTRL,                   // 78
        MMI_DDR_BB_TRAFFIC,             // 79
        MMI_DDR_BB_PERF,                // 80
        MMI_ITRANS_SYS0,                // 81
        MMI_ITRANS_SYS1,                // 82
        MMI_ITRANS_BP,                  // 83
        MMI_ITRANS_HDR,                 // 84
        MMI_ITRANS_KAS,                 // 85
        MMI_SATA1_CTRL,                 // 86
        MMI_SATA2_CTRL,                 // 87
        MMI_SATA3_CTRL,                 // 88
        MMI_SATA_INIT_CTRL,             // 89
        MMI_SATA1_DRP,                  // 90
        MMI_SATA2_DRP,                  // 91
        MMI_SATA3_DRP,                  // 92
        MMI_SATA1_PERF,                 // 93
        MMI_SATA2_PERF,                 // 94
        MMI_SATA3_PERF,                 // 95
        MMI_SATA_BLOCK_TRAFFIC_GEN,     // 96
        MMI_SATA1_BLOCK_TRAFFIC_GEN,    // 97
        MMI_SATA2_BLOCK_TRAFFIC_GEN,    // 98
        MMI_SATA3_BLOCK_TRAFFIC_GEN,    // 99
        MMI_RX_BB_FRAME_COUNTER,        // 100
        MMI_RX_BB_ERROR_COUNTER,        // 101
        MMI_ETH_NIC_SRC_PROFILER,       // 102
        MMI_ETH_NIC_SINK_PROFILER,      // 103
        MMI_ETH_RGMII_SRC_PROFILER,     // 104
        MMI_ETH_RGMII_SINK_PROFILER,    // 105
        MMI_ETH_RXSDR_SRC_PROFILER,     // 106
        MMI_ETH_TXSDR_SINK_PROFILER,    // 107
        MMI_KAS_CPM,                    // 108
        MMI_KAS_CPM_VLIM,               // 109
        MMI_KAS_CPM_MAXVAL,             // 110
        MMI_KAS_SYNTHRX,                // 111
        MMI_KAS_SYNTHTX,                // 112
        MMI_KAS_IQMOD,                  // 113
        MMI_KAS_DAC,                    // 114
        MMI_KAS_ADC,                    // 115
        MMI_KAS_I2C,                    // 116
        MMI_DSSS_RX_CTRL,               // 117
        MMI_DSSS_DEMODULATOR,           // 118
        MMI_DSSS_FEC_DECODER,           // 119
        MMI_TX_DVBS2X_DATA_FRAMER,      // 120
        MMI_TX_DVBS2X_MOD,              // 121
        MMI_TX_DVBS2X_SYMB_RATE_DIV,    // 122
        MMI_TX_EQ_REAL,                 // 123
        MMI_TX_EQ_IMAG,                 // 124
        MMI_TX_ALC,                     // 125
        MMI_KAS_NANO_DAC,               // 126
        MMI_NDEVS
    } mmi_devices_t;

    parameter bit [MMI_ADDRLEN-1:0] DEV_OFFSET [0:MMI_NDEVS] = '{
        15'h0000,     //  0: HSD Controller
        15'h0080,     //  1: SSD to OBC bulk transfer
        15'h00A0,     //  2: OBC to SSD bulk transfer
        15'h00C0,     //  3: NIC RX DBUF
        15'h00D0,     //  4: NIC TX DBUF
        15'h00E0,     //  5: IRQ Controller
        15'h0100,     //  6: SEM Controller
        15'h0110,     //  7: Temp Controller Sensor lm71
        15'h0114,     //  8: Temp Controller Sensor lm71
        15'h0118,     //  9: LMK CTRL
        15'h0120,     // 10: FE ADC
        15'h01C0,     // 11: Zynq Firewall event FIFO
        15'h01D0,     // 12: MMI Firewall event FIFO
        15'h01E8,     // 13: MMI Firewall status bits
        15'h01F0,     // 14: Zynq axi_lpd_s bus
        15'h0200,     // 15: Alarm Monitor
        15'h2000,     // 16: Current Monitors
        15'h2100,     // 17: Current Monitors
        15'h0300,     // 18: RX ADC
        15'h0320,     // 19: RX AMP
        15'h0340,     // 20: RX ADC DATA
        15'h0360,     // 21: RX DATA
        15'h0380,     // 22: RX DSP
        15'h03A0,     // 23: RX Demodulator - UPI
        15'h03B0,     // 24: RX ADC FIFO
        15'h03C0,     // 25: TX data
        15'h03D0,     // 26: TX DSP
        15'h03E0,     // 27: TX Modulator - UPI
        15'h0400,     // 28: TXSDR input buffer (for testing)
        15'h0420,     // 29: Rx power monitor (before filter)
        15'h0430,     // 30: Rx power monitor (after filter)
        15'h0440,     // 31: UPI polling
        15'h0460,     // 32: Filter baseband packets based on BB header
        15'h0500,     // 33: DAC
        15'h0600,     // 34: DAC JESD control registers
        15'h0800,     // 35: FE synthesizer rx
        15'h0880,     // 36: FE synthesizer tx
        15'h0B00,     // 37: PCH LM71 temperature limits
        15'h0B02,     // 38: ADS1118 temperarate limits (ADC and PA)
        15'h0B04,     // 39: ADS1015 temperarate limits (PA and board)
        15'h0B80,     // 40: Scratch registers for general software use
        15'h0AF0,     // 41: IRQ software test generator
        15'h2300,     // 42: HDR current monitors
        15'h1100,     // 43: Backplane IO Expander
        15'h1110,     // 44: AXIS to RGMII bridge
        15'h1118,     // 45: MDIO for PL-side ethernet PHY
        15'h1140,     // 46: Second backplane IO expander
        15'h1000,     // 47: Backplane Current Monitors
        15'h1440,     // 48: NIC SDR
        15'h1480,     // 49: P4 Forwarding control plane
        15'h1490,     // 50: MPLS Simpletoga
        15'h14A0,     // 51: MPLS Router
        15'h1800,     // 52: NICHDR_CTRL
        15'h1900,     // 53: RFoE controller
        15'h3E00,     // 54: SATA SSD interface
        15'h3E20,     // 55: DRP to MMI for SATA xcvr
        15'h3E40,     // 56: SATA performance counters
        15'h3E60,     // 57: SATA test traffic generator
        15'h3E80,     // 58: Copy data between any two BlockByte devices
        15'h3EA0,     // 59: PS-side SSD power control
        15'h1600,     // 60: Zynq Ultrascale Sysmon DRP Registers
        15'h1680,     // 61: CPU-based QSPI block interface
        15'h16A0,     // 62: IRQ Controller for PS
        15'h16C0,     // 63: IRQ software test generator
        15'h1700,     // 64: QSPI block byte device
        15'h1720,     // 65: QSPI test traffic generator
        15'h1740,     // 66: QSPI performance counters
        15'h2500,     // 67: Voltage limit control for CPM
        15'h2510,     // 68: Voltage limit control for CPM
        15'h2530,     // 69: Voltage limit control for CPM
        15'h2540,     // 70: Voltage limit control for CPM
        15'h2580,     // 71: Maximum value recording for CPM
        15'h25A0,     // 72: Maximum value recording for CPM
        15'h25E0,     // 73: Maximum value recording for CPM
        15'h2600,     // 74: Maximum value recording for CPM
        15'h26A0,     // 75: TX sample replay from SSD
        15'h26C0,     // 76: Generates IQ samples
        15'h2870,     // 77: I2C clock divider control
        15'h2880,     // 78: DDR CTRL
        15'h28A0,     // 79: DDR Block layer test traffic generator
        15'h28C0,     // 80: DDR BB performance counters
        15'h4000,     // 81: current transients sys0
        15'h4010,     // 82: current transients sys1
        15'h4020,     // 83: current transients bp
        15'h4030,     // 84: current transients hdr
        15'h4040,     // 85: current transients kas
        15'h4100,     // 86: SATA SSD interface
        15'h4120,     // 87: SATA SSD interface
        15'h4140,     // 88: SATA SSD interface
        15'h4160,     // 89: Multiple SATA stack init control
        15'h4168,     // 90: DRP to MMI for SATA xcvr
        15'h4170,     // 91: DRP to MMI for SATA xcvr
        15'h4178,     // 92: DRP to MMI for SATA xcvr
        15'h4180,     // 93: SATA performance counters
        15'h4188,     // 94: SATA performance counters
        15'h4190,     // 95: SATA performance counters
        15'h41A0,     // 96: SATA test traffic generator
        15'h41C0,     // 97: SATA test traffic generator
        15'h41E0,     // 98: SATA test traffic generator
        15'h4200,     // 99: SATA test traffic generator
        15'h4350,     // 100: BB Frame Counter
        15'h4370,     // 101: BB Error Counter
        15'h4600,     // 102: NIC ethernet source profiler"
        15'h4610,     // 103: NIC ethernet sink profiler"
        15'h4620,     // 104: RGMII ethernet source profiler"
        15'h4630,     // 105: RGMII ethernet sink profiler"
        15'h4640,     // 106: RXSDR ethernet source profiler"
        15'h4650,     // 107: TXSDR ethernet sink profiler"
        15'h4700,     // 108: KAS current monitors
        15'h4780,     // 109: Voltage limit control for CPM
        15'h47A0,     // 110: Maximum value recording for CPM
        15'h4800,     // 111: FE synthesizer rx
        15'h4880,     // 112: FE synthesizer tx
        15'h4900,     // 113: ADMV1013
        15'h4910,     // 114: AD5601
        15'h4940,     // 115: Actually an ads1115 for PA temperature and TX power detector
        15'h4980,     // 116: KaS I2C bus controller
        15'h49C0,     // 117: DSSS RX channel controler
        15'h4A40,     // 118: DSSS demodulator
        15'h4A90,     // 119: DSSS FEC decoder
        15'h4B00,     // 120: DVBS2X TX Data Framer
        15'h4B20,     // 121: DVBS2X Modulator
        15'h4B30,     // 122: DVB-S2X symbol rate divider control
        15'h4B40,     // 123: TX EQ: real coefficients
        15'h4B60,     // 124: TX EQ: imaginary coefficients
        15'h4BA0,     // 125: TX automatic level control
        15'h4BA8,     // 126: KAS AGC DAC
        15'h4BAC      //      next free address
    };

    parameter int DEV_WIDTH [0:MMI_NDEVS] = '{
         6,     // MMI_HSDCTRL
         5,     // MMI_OBC_SSD_READ
         5,     // MMI_OBC_SSD_WRITE
         4,     // MMI_TDI_RXDBUF
         4,     // MMI_TDI_TXDBUF
         4,     // MMI_IRQCTRL
         3,     // MMI_SEMCTRL
         2,     // MMI_LM71CTRL0
         2,     // MMI_LM71CTRL1
         3,     // MMI_LMKCLK
         3,     // MMI_FE_ADC
         4,     // MMI_ZYNQ_FW_EVENTS
         4,     // MMI_MMI_FW_EVENTS
         3,     // MMI_MMI_FW
         4,     // MMI_PS_MASTER
         7,     // MMI_GLOBAL_ALARM
         8,     // MMI_CPMCTRL0
         8,     // MMI_CPMCTRL1
         4,     // MMI_RXADC
         5,     // MMI_RXAMP
         5,     // MMI_RXADCDATA
         5,     // MMI_RXDATA
         5,     // MMI_RXDSP
         3,     // MMI_UPI_RXDEMOD
         4,     // MMI_RXFIFO
         4,     // MMI_TXDATA
         4,     // MMI_TXDSP
         3,     // MMI_UPI_TXMOD
         3,     // MMI_TXSDR_TXBUF
         4,     // MMI_RX_PWR_PREFILT
         4,     // MMI_RX_PWR_POSTFILT
         3,     // MMI_UPI_POLL
         5,     // MMI_RX_BBFILT
         8,     // MMI_TXDAC
         3,     // MMI_TXDAC_JESD
         7,     // MMI_FE_SYNTHRX
         7,     // MMI_FE_SYNTHTX
         1,     // MMI_PCH_TEMP_LIMIT
         1,     // MMI_HDR_TEMP_LIMIT
         2,     // MMI_KAS_TEMP_LIMIT
         4,     // MMI_SCRATCH
         0,     // MMI_IRQ_TEST
         7,     // MMI_HDR_CPM
         3,     // MMI_BP_IO
         3,     // MMI_RGMII
         2,     // MMI_MDIO_CTRL
         3,     // MMI_BP_IO_SEC
         8,     // MMI_BP_CPM
         6,     // MMI_NIC_SDR
         3,     // MMI_P4_FWD
         4,     // MMI_MPLS_SIMPLETOGA
         5,     // MMI_MPLS_ROUTER
         8,     // MMI_NICHDR_CTRL
         6,     // MMI_RFOE_CTRL
         5,     // MMI_SATA_CTRL
         3,     // MMI_SATA_DRP
         3,     // MMI_SATA_PERF
         5,     // MMI_SATA_TRAFFIC_GEN
         5,     // MMI_IDEV_COPY
         2,     // MMI_PS_SSD_CTRL
         7,     // MMI_SYSMON
         5,     // MMI_ZYNQ_SOFT_QSPI
         4,     // MMI_PSIRQCTRL
         0,     // MMI_ZYNQ_IRQ_TEST
         5,     // MMI_QSPI_BB
         5,     // MMI_QSPI_TRAFFIC_GEN
         3,     // MMI_QSPI_PERF
         4,     // MMI_CPMCTRL0_VLIM
         4,     // MMI_CPMCTRL1_VLIM
         3,     // MMI_HDR_CPM_VLIM
         4,     // MMI_BP_CPM_VLIM
         5,     // MMI_CPMCTRL0_MAXVAL
         5,     // MMI_CPMCTRL1_MAXVAL
         5,     // MMI_HDR_CPM_MAXVAL
         5,     // MMI_BP_CPM_MAXVAL
         4,     // MMI_TXREPLAY
         3,     // MMI_TXNCO
         2,     // MMI_I2C_CLK_DIV
         4,     // MMI_DDR_CTRL
         5,     // MMI_DDR_BB_TRAFFIC
         3,     // MMI_DDR_BB_PERF
         4,     // MMI_ITRANS_SYS0
         4,     // MMI_ITRANS_SYS1
         4,     // MMI_ITRANS_BP
         4,     // MMI_ITRANS_HDR
         4,     // MMI_ITRANS_KAS
         5,     // MMI_SATA1_CTRL
         5,     // MMI_SATA2_CTRL
         5,     // MMI_SATA3_CTRL
         3,     // MMI_SATA_INIT_CTRL
         3,     // MMI_SATA1_DRP
         3,     // MMI_SATA2_DRP
         3,     // MMI_SATA3_DRP
         3,     // MMI_SATA1_PERF
         3,     // MMI_SATA2_PERF
         3,     // MMI_SATA3_PERF
         5,     // MMI_SATA_BLOCK_TRAFFIC_GEN
         5,     // MMI_SATA1_BLOCK_TRAFFIC_GEN
         5,     // MMI_SATA2_BLOCK_TRAFFIC_GEN
         5,     // MMI_SATA3_BLOCK_TRAFFIC_GEN
         4,     // MMI_RX_BB_FRAME_COUNTER
         4,     // MMI_RX_BB_ERROR_COUNTER
         4,     // MMI_ETH_NIC_SRC_PROFILER
         4,     // MMI_ETH_NIC_SINK_PROFILER
         4,     // MMI_ETH_RGMII_SRC_PROFILER
         4,     // MMI_ETH_RGMII_SINK_PROFILER
         4,     // MMI_ETH_RXSDR_SRC_PROFILER
         4,     // MMI_ETH_TXSDR_SINK_PROFILER
         7,     // MMI_KAS_CPM
         3,     // MMI_KAS_CPM_VLIM
         5,     // MMI_KAS_CPM_MAXVAL
         7,     // MMI_KAS_SYNTHRX
         7,     // MMI_KAS_SYNTHTX
         4,     // MMI_KAS_IQMOD
         4,     // MMI_KAS_DAC
         6,     // MMI_KAS_ADC
         6,     // MMI_KAS_I2C
         5,     // MMI_DSSS_RX_CTRL
         6,     // MMI_DSSS_DEMODULATOR
         4,     // MMI_DSSS_FEC_DECODER
         5,     // MMI_TX_DVBS2X_DATA_FRAMER
         3,     // MMI_TX_DVBS2X_MOD
         2,     // MMI_TX_DVBS2X_SYMB_RATE_DIV
         5,     // MMI_TX_EQ_REAL
         5,     // MMI_TX_EQ_IMAG
         3,     // MMI_TX_ALC
         2,     // MMI_KAS_NANO_DAC
         0
    };

endpackage

`default_nettype wire
